services:
  db:
    image: postgres:latest
    container_name: restaurant_db
    restart: always
    environment:
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_password
      POSTGRES_DB: restaurant_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U restaurant_user -d restaurant_db" ]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    container_name: restaurant_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://restaurant_user:restaurant_password@db:5432/restaurant_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:
